# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=200)),
                ('currentPrice', models.FloatField()),
            ],
        ),
    ]
