# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 20:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InvestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etf',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etf',
            name='currentPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
