# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 19:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InvestApp', '0002_auto_20170528_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountName', models.CharField(max_length=200)),
                ('accountType', models.CharField(max_length=200)),
                ('totalCashValue', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('totalStockValue', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('totalAccountValue', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvestApp.Account')),
                ('etfID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvestApp.etf')),
            ],
        ),
    ]
