# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvestApp', '0003_account_accountbreakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbreakdown',
            name='accountID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvestApp.account'),
        ),
        migrations.AlterField(
            model_name='accountbreakdown',
            name='etfID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvestApp.etf'),
        ),
    ]
