# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvestApp', '0004_auto_20170529_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='accountName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='accountType',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='accountbreakdown',
            name='accountID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvestApp.account'),
        ),
        migrations.AlterField(
            model_name='accountbreakdown',
            name='etfID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvestApp.etf'),
        ),
    ]
